### ISSUE TITLE
Doctor registration is not working

### ISSUE THREAD

**Issue by majidkhan138** [thegr8dev/doctorpatientportal#1]
Hello Sir ..i am registering doctor ..when i fill the form and click on register button an empty windows show and when i check no doctor is registered ..
what is the problem ??

**Comment by thegr8dev** [comment]
Hello, @majidkhan138 thanks for open an issue.  I'm checking your issue can you elaborate your issue with steps? it's help me to resolve issue quickly :)

**Comment by thegr8dev** [comment]
## Kindly check 

1. under includes/conn.php "dpp" is selected as database (if your database is different than change it there too)
2. Javascript is enabled in your browser (use chrome or firefox for it.)
3. Xammp or wamp is installed successfully in your pc.

**Comment by majidkhan138** [comment]
Hello Sir.. Thanks for your time the problem is resolved... And Sir can you
add donate organ in patient dashboard and search organ in doctor
dashboard...??
This is one of the best portal i have ever seen.. Only the organ donation
will make it more good

**Comment by thegr8dev** [comment]
Okay will add soon

**Comment by majidkhan138** [comment]
Ok Sir... Let me inform when you add it...
