### ISSUE TITLE
Doctor registeration and login is not working

### ISSUE THREAD

**Issue by shrishti140601** [thegr8dev/doctorpatientportal#5]
Doctor registeration and login is not working, what to do?

**Comment by winstonhong** [comment]
A simple solution is downgrade your PHP 5.

I can confirm that this repository worked well for the following PHP version.

php -v
PHP 5.5.9-1ubuntu4.20 (cli) (built: Oct 3 2016 13:01:18)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans

New PHP library is incompatible with some codes.

**Comment by Marvellye** [comment]
hello, please is there a way to use the dp.php on php 7?

**Comment by winstonhong** [comment]
If you want to use the dp.php on PHP 7, you need to modify the source code. 

You can fork the branch and then revise the source code.

**Comment by Marvellye** [comment]
iv'e tried but i still got the same result. please maybe you can be of help on modifying the source code.... thanks :)
